import os
import shutil
import subprocess
import sys
import tempfile
from os import walk
import yaml
import regex

# The Substrait extension definitions are consumed from the substrait-extensions
# C++ package published by substrait-packaging. Bump this tag (in lockstep with
# the substrait-protobuf GIT_TAG in CMakeLists.txt) to update the Substrait
# version, then re-run this script and commit the regenerated
# src/custom_extensions_generated.cpp.
SUBSTRAIT_PACKAGING_REPO = "https://github.com/substrait-io/substrait-packaging.git"
SUBSTRAIT_EXTENSIONS_TAG = "cpp/substrait-extensions/v0.89.0"
SUBSTRAIT_EXTENSIONS_SUBDIR = os.path.join("cpp", "substrait-extensions", "extensions")


def parse_function_data(functions,yaml_data,function_type):
	for function_data in yaml_data.get(function_type, []):
		function = {
			'name': function_data['name'],
			'impls_args': []
		}

		for implementation in function_data.get('impls', []):
			args = []
			for arg in implementation.get('args', []):
				arg_info = {'name': arg.get('name', ''), 'value': arg.get('value', '')}
				args.append(arg_info)

			function['impls_args'].append(args)

		functions.append(function)
	return functions

def parse_yaml(file_path):
	with open(file_path, 'r') as file:
		yaml_data = yaml.safe_load(file)
	functions = []
	functions = parse_function_data(functions,yaml_data,'scalar_functions')
	functions = parse_function_data(functions,yaml_data,'aggregate_functions')
	functions = parse_function_data(functions,yaml_data,'window_functions')
	return functions

def get_custom_functions(custom_extension_folder):
	inner_code = ""
	type_set = set()
	custom_function_paths = next(walk(custom_extension_folder), (None, None, []))[2]
	for custom_function_path in custom_function_paths:
		functions = parse_yaml(os.path.join(custom_extension_folder,custom_function_path))
		for function in functions:
			for impls_args in function["impls_args"]:
				type_str = "{"
				for args in impls_args:
					type_value = regex.sub(r'<[^>]*>', '', args["value"])
					if (len(type_value) != 0):
						type_set.add(type_value)
						type_str += f"\"{type_value}\","
				# Remove trailing comma if present
				if type_str.endswith(","):
					type_str = type_str[:-1]
				type_str += "}"
				function_name = function["name"]
				# The Substrait extension URN identifies the extension by its
				# bare name (extension:<owner>:<id>), not the YAML file path, so
				# drop the .yaml suffix.
				extension_id = os.path.splitext(custom_function_path)[0]
				inner_code += f"\tInsertCustomFunction(\"{function_name}\", {type_str}, \"{extension_id}\");\n"
	print(type_set)
	return inner_code

def write_custom_extension_file(custom_functions):
	file_path  = os.path.join(os.path.dirname(os.path.realpath(__file__)),'..','src','custom_extensions_generated.cpp')
	header = '''#include "custom_extensions/custom_extensions.hpp"

//! This class is auto-generated by scripts/generate_custom_functions.py
//! It depends on the substrait-extensions extensions/*.yaml files
namespace duckdb{

void SubstraitCustomFunctions::Initialize(){
	'''
	footer = '''}

} // namespace duckdb'''

	# Open the file in write mode
	with open(file_path, 'w') as file:
	# Write new content to the file
		file.write(header)
		file.write(custom_functions)
		file.write(footer)

def resolve_extensions_folder():
	"""Return the directory holding the Substrait extension YAML files.

	If a path is passed on the command line (e.g. a local substrait-packaging
	checkout's extensions dir, or a FetchContent-populated SubstraitExtensions
	data dir), use it. Otherwise shallow-clone substrait-packaging at
	SUBSTRAIT_EXTENSIONS_TAG and use its vendored extensions dir. The caller is
	responsible for cleaning up the returned temp dir via the second return
	value (None when a user-provided path is used).
	"""
	if len(sys.argv) > 1:
		return sys.argv[1], None

	tmp_dir = tempfile.mkdtemp(prefix="substrait-extensions-")
	print(f"Cloning {SUBSTRAIT_PACKAGING_REPO} @ {SUBSTRAIT_EXTENSIONS_TAG}")
	subprocess.run(
		["git", "clone", "--depth", "1", "--branch", SUBSTRAIT_EXTENSIONS_TAG,
		 SUBSTRAIT_PACKAGING_REPO, tmp_dir],
		check=True,
	)
	return os.path.join(tmp_dir, SUBSTRAIT_EXTENSIONS_SUBDIR), tmp_dir

extensions_folder, tmp_dir = resolve_extensions_folder()
try:
	functions = get_custom_functions(extensions_folder)
	write_custom_extension_file(functions)
finally:
	if tmp_dir is not None:
		shutil.rmtree(tmp_dir, ignore_errors=True)
