name: C Unit tests

on: [push, pull_request,repository_dispatch]

defaults:
  run:
    shell: bash

jobs:
  unitTests:
    name: C unit tests
    runs-on: macos-latest
    env:
      GEN: ninja

    steps:
    - name: Install Ninja
      run: brew install ninja

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Build Substrait with C unit test
      run: make release_c_unit_test

    - name: Run C unit tests
      run: ./build/release/extension/substrait/test/c/test_substrait_exe
