#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Stable Extension Distribution Pipeline
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@b777c70d30942cca5bef62d6d4fa23a13362f398
    with:
      duckdb_version: d8cdaa33fda8df955cc76ef58a280f68f4cd43fa
      ci_tools_version: b777c70d30942cca5bef62d6d4fa23a13362f398
      exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64;windows_amd64_mingw"
      extension_name: substrait

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@b777c70d30942cca5bef62d6d4fa23a13362f398
    secrets: inherit
    with:
      duckdb_version: d8cdaa33fda8df955cc76ef58a280f68f4cd43fa
      ci_tools_version: b777c70d30942cca5bef62d6d4fa23a13362f398
      exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64;windows_amd64_mingw"
      extension_name: substrait
      deploy_latest: true
